export const ERROR_CODES = {
  VALIDATION_FAILED: "VALIDATION_FAILED",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  RATE_LIMITED: "RATE_LIMITED",
  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
  TRIP_NOT_ACTIVE: "TRIP_NOT_ACTIVE",
  TRIP_IN_PAST: "TRIP_IN_PAST",
  NO_CAR: "NO_CAR",
  SEAT_TAKEN: "SEAT_TAKEN",
  ALREADY_BOOKED: "ALREADY_BOOKED",
  ALREADY_REVIEWED: "ALREADY_REVIEWED",
  NOT_PARTICIPANT: "NOT_PARTICIPANT",
  SELF_REVIEW: "SELF_REVIEW",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export interface ApiErrorBody {
  code: ErrorCode;
  message: string;
  errors?: unknown;
}
